logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/MatadorProBr/revanced-extended-magisk-module/blob/main/CONFIG.md for more detailed explanations

[YouTube]
build-mode = "both"                                                                                      # 'both', 'apk' or 'module'
excluded-patches = "custom-branding-icon-revancify-blue custom-branding-youtube-name"                    # space-seperated patches to exclude (multiline strings are not supported)
included-patches = "add-splash-animation materialyou"                                                    # space-seperated patches to include (non-excluded patches are included by default)
version = "auto"                                                                                         # 'auto', 'latest', 'beta' or a custom one like '17.45.36'
apkmirror-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Music]
build-mode = "both"
excluded-patches = "'Custom branding Music name' 'Custom branding icon Revancify blue'"
included-patches = "'Add splash animation' 'MaterialYou'"
apkmirror-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
apkmirror-arch = "both"                                                                                  # both arm64-v8a and arm-v7a

[Reddit]
enabled = false
apkmirror-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"
