logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/AbakNacchan/revanced-extended/blob/revanced-extended/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
build-mode = "both"
excluded-patches = "'Announcements' 'Custom branding icon YouTube' 'Custom branding name YouTube'"
included-patches = "'Add splash animation' 'MaterialYou' 'Remove player controls background'"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
arch = "both"
apkmirror-arch = "both"

[Music]
build-mode = "both"
excluded-patches = "'Custom branding icon YouTube Music' 'Custom branding name YouTube Music'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
apkmirror-arch = "both"
included-patches = "'Compact header' 'Permanent shuffle' 'Permanent repeat'"
excluded-patches = "'Remove upgrade button'"
