['patch-options']
YouTubeAppName = "ReVanced Extended"
YouTubePackageName = "app.rvx.android.youtube"
MusicPackageName = "app.rvx.android.apps.youtube.music"
MusicDownloaderPackageName = "com.junkfood.seal"
CustomSpeedArrays = "0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2.0, 2.25, 2.5, 3.0, 5.0"
OverlayButtonsIcon = "new"
darkThemeBackgroundColor = "@android:color/black"
clientSpoofVersion = "17.28.35"